name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'pnpm'
            cache-dependency-path: |
              frontend/pnpm-lock.yaml
              backend/pnpm-lock.yaml
      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install deps (frontend)
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile
      - name: Build (frontend)
        working-directory: ./frontend
        run: pnpm build

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            backend/pnpm-lock.yaml
      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install deps (backend)
        working-directory: ./backend
        run: pnpm install --frozen-lockfile
      - name: Test (backend)
        working-directory: ./backend
        run: pnpm test --if-present --reporter=verbose -- --run


